[package]
name = "cairo_course_exercises"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.29.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.16.0" } 
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev="82088715b454d8cf197b9c54c31525ca0cb57a05" }
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev="82088715b454d8cf197b9c54c31525ca0cb57a05" }
alexandria_sorting = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "82088715b454d8cf197b9c54c31525ca0cb57a05" }
starknet = "2.8.0"
assert_macros = "2.8.0"


[[target.starknet-contract]]
casm = true
allowed-libfuncs-list.name = "experimental"

[sncast.account1]
account = "account1"
accounts-file = "/Users/jonathanshahak/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"

[cairo]
allow-warnings = true

[[tool.snforge.fork]]
name = "MAINNET_FORK_609051"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"
block_id.number = "609051"

[tool.fmt]
max-line-length = 140