mod basic_types;
mod control_flow;
mod functions;
// mod advanced_types;
// mod first_cairo_contract;
// mod starknet_foundry;
// mod erc20;
// mod erc721;
// mod ownership;
// mod components;
// mod visibility;